### PR TITLE
Made sure than head-movement eventually gets its poses transformed

### PR DESCRIPTION
**Pull request by fairlight1337**
Head-movement should never fail; that's why tf transformations are trying indefinitely.

### CODE REVIEW

**Comment by gaya-** [comment]
I don't see a point of using an infinite loop here. Just set an enormous timeout in `transform-pose-stamped instead` of the default timeout. The function will retry as many times to look up the transform until the enormous timeout is reached.
Infinite loops are the very last resort, in my opinion, and should be avoided at all costs (unless it's your program loop).

**Comment by fairlight1337** [comment]
Hm, good point. I'll refactor it and add the `:timeout` option to the head-movement designator at some point, but then I'll use the `*tf-default-timeout*` for that for now.

Thanks for the input, you're right.

**Comment by gaya-** [comment]
Already merged with https://github.com/cram2/cram_pr2/pull/10

**Comment by fairlight1337** [comment]
Yeah, that was an accident, sorry about that. I removed the loop in https://github.com/cram2/cram_pr2/pull/11. Thanks for the notice, this somehow got into the wrong branch.

**Pull request closed without merging**
