### PR TITLE
Moveit, Giskard integration

### PR DESCRIPTION
**Pull request by mpomarlan**
Refactoring of the manipulation process module code to be able to use either giskard, or moveit (or any other motion generators we might have in the future).

If you want to test/use this version of the code, you will also need 

https://github.com/mpomarlan/cram_motion_manager/
https://github.com/mpomarlan/cram_moveit_manager/
https://github.com/mpomarlan/cram_giskard_manager/

loaded. 

This pull request should not be merged yet; test the code here (and the managers) please, and we will look into merging after.

### CODE REVIEW

**Comment by fairlight1337** [comment]
I'm trying it out on the longterm fetch and place right now. It seems as if moving the arms in principle works (I didn't load `cram_giskard_manager`, but only `cram_moveit_manager`), but grasping fails. There are no checks for reachability anymore, which leads me to the naive conclusion that either the reaching-length or the movement planning call is not behaving as expected. I will check in more detail later today.

**Comment by mpomarlan** [comment]
On the raise-elbow issue, I pushed a new commit that should fix it. 

Basically, I thought raise-elbow is supposed to be T/nil for the arm currently being planned for, but it's supposed to be :left, :right, or nil. So the error appeared because I was sending T (because the higher level, for some but only some plans, sends raise-elbow requests for some arms). I'm now sending the side (:left or :right) that I am getting.

**Comment by fairlight1337** [comment]
Awesome, I'll take a good look at it later, together with the other issue we talked about earlier.

**Comment by fairlight1337** [comment]
So from my point of view, this can be merged. I tried it with the repositories above and adapted the longterm fetch and place scenario to it; everything works as expected.

**Pull request merged**
